### ISSUE TITLE
up_integration-test-env.ps1 does not start all services

### ISSUE THREAD

**Issue by siudeks** [eventflow/EventFlow#664]
### Problem: 
As a developer, I would like to start ElasticSearch using provided **up_integration-test-env.ps1** so that I can start integration tests related to ElasticSearch

Reproduction:
* Use Docker with Windows Containers
* Run up_integration-test-env.ps1 as described in *README.md*

Expected
* ElasticSearch service is started as docker container

Actual:
* ElasticSearch container is stopped
* in logs is description I see error message:
```
'\".\bin\elasticsearch.bat\"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by siudeks** [comment]
Hello @rasmus, is anyone looking for the issue, or I can start investigate it?

**Comment by rasmus** [comment]
@siudeks sure, I have a long summer holiday this year and don't access GitHub that often during the holidays

**Comment by siudeks** [comment]
Happy man :) I will try to fix till 07/21 in my spare time

**Comment by siudeks** [comment]
Investingations in progress, update:

***docker-compose -f docker-compose.ci.yml up -d*** runs elasticsearch with error *'\".\bin\elasticsearch.bat\"' is not recognized as an internal or external command,
operable program or batch file.*

Not sure why it doesn't work

next try:
let's start changing docker-compose.ci.yml
```docker-compose
services:
  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    container_name: elasticsearch-ef
    command: bin\\elasticsearch.bat
```

***docker-compose -f docker-compose.ci.yml up -d***
started! *but* elasticsearch doesn't work, in logs we see
*Error occurred during initialization of VM
Could not reserve enough space for object heap*

Let's try to increase memory ... unfortunately I don't see working option with increasing memory with docker-compose and windows container. Let's start with pure docker cli:
***docker run -m 3G -p 9200:9200 sixeyed/elasticsearch:5.6.0-nanoserver-sac2016 bin\elasticsearch.bat***

With this workaround **is working! Project integration tests related to elasticsearch are green :)**

**Comment by siudeks** [comment]
@rasmus I don't see how to run elasticsearch from docker-compose based on my findings above. If you need some help let me know

**Comment by rasmus** [comment]
The memory settings isn't in the Docker compose files shipped with EventFlow, its on your VM for your own Docker settings. Here's mine.

![image](https://user-images.githubusercontent.com/18956/61373177-689b9480-a899-11e9-958b-2af02f66128f.png)

I have 32 GB RAM on my work station and thus allocate quite a lot

**Comment by rasmus** [comment]
Note that the "Disk image max size" may also put some limits on your VM as it limits e.g. the amount of images you can pull. I also recommend increasing it

**Comment by rasmus** [comment]
I you can verify that this is indeed the problem, then I'll add a note in the README regarding increase of memory

**Comment by rasmus** [comment]
Hopefully Windows Server will get Linux container support soon, making it possible for the integration tests to use Linux containers instead

**Comment by siudeks** [comment]
Correct me if I'm wrong, but what you just screenshotted is Docker for Linux containers, but whole CI solution is designed for Windows containers without memory settings

![image](https://user-images.githubusercontent.com/3256574/61393501-64836d00-a8c1-11e9-831b-2985b10e22b1.png)

**Comment by rasmus** [comment]
You are absolutely correct, doh.

**Comment by ProH4Ck** [comment]
I solved switching to linux containers and using the following docker-compose.yml

```
version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ef
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch-ef
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  eventstore:
    image: eventstore/eventstore
    container_name: eventstore-ef
    ports:
      - "1113:1113"
      - "2113:2113"
```

It uses official docker images
